apiVersion: v1
kind: Service
metadata:
  name: myaapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: web      ///in selector you can add which pod will use this services 
 
